### ISSUE TITLE
Unable to instrument custom scripts

### ISSUE THREAD

**Issue by ryanwi** [appneta/oboe-ruby#112]
Using [the example](https://gist.github.com/pglombardo/8550713) provided in the README to instrument custom scripts, the following error is encountered.

```
/home/user/.gem/ruby/2.1.5/gems/oboe-2.7.15.1/lib/oboe/ruby.rb:23:in `load': uninitialized constant Oboe::Inst (NameError)
        from /home/user/.gem/ruby/2.1.5/gems/oboe-2.7.15.1/lib/oboe/ruby.rb:12:in `initialize'
        from script.rb:13:in `<main>'
```

**Comment by ryanwi** [comment]
After installing the traceview OS libraries and running `gem pristine oboe` the problem has been resolved.

**Comment by pglombardo** [comment]
Great that it's resoved but this error shouldn't have happened anyways.  To be fixed in https://github.com/appneta/oboe-ruby/issues/113.  Thanks @ryanwi !
